CREATE TABLE header_images (
  id TIMESTAMP PRIMARY KEY DEFAULT CURRENT_TIMESTAMP,
  header_id TIMESTAMP NOT NULL,
  image_url VARCHAR(255) NOT NULL,
  link_url VARCHAR(255) DEFAULT NULL,
  alt_text VARCHAR(100) DEFAULT '',
  sort_order INT DEFAULT 0,
  FOREIGN KEY (header_id) REFERENCES header(id) ON DELETE CASCADE
);

CREATE TABLE footer_images (
  id TIMESTAMP PRIMARY KEY DEFAULT CURRENT_TIMESTAMP,
  footer_id TIMESTAMP NOT NULL,
  image_url VARCHAR(255) NOT NULL,
  link_url VARCHAR(255) DEFAULT NULL,
  alt_text VARCHAR(100) DEFAULT '',
  sort_order INT DEFAULT 0,
  FOREIGN KEY (footer_id) REFERENCES footer(id) ON DELETE CASCADE
);